// tslint:disable
/**
 * Bordex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceOrderCreateDto
 */
export interface DeviceOrderCreateDto {
    /**
     * 
     * @type {string}
     * @memberof DeviceOrderCreateDto
     */
    hostname: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceOrderCreateDto
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceOrderCreateDto
     */
    site: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceOrderCreateDto
     */
    vendor: string;
}


