// tslint:disable
/**
 * Bordex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceInterfaceUpdateDto
 */
export interface DeviceInterfaceUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof DeviceInterfaceUpdateDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceInterfaceUpdateDto
     */
    ipAddressV4?: string | null;
}


