// tslint:disable
/**
 * Bordex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DeviceModelDto } from './device-model-dto';
import { OrderDto } from './order-dto';
import { SiteDto } from './site-dto';

/**
 * 
 * @export
 * @interface DeviceDto
 */
export interface DeviceDto {
    /**
     * 
     * @type {number}
     * @memberof DeviceDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceDto
     */
    hostname: string;
    /**
     * 
     * @type {DeviceModelDto}
     * @memberof DeviceDto
     */
    model: DeviceModelDto;
    /**
     * One of the following: Unknown, Offline, Active, Planned, Staged, Failed, Inventory, Decommissioning.
     * @type {string}
     * @memberof DeviceDto
     */
    status: string;
    /**
     * 
     * @type {SiteDto}
     * @memberof DeviceDto
     */
    site: SiteDto;
    /**
     * 
     * @type {string}
     * @memberof DeviceDto
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceDto
     */
    managementIpAddress?: string | null;
    /**
     * 
     * @type {OrderDto}
     * @memberof DeviceDto
     */
    order?: OrderDto;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceDto
     */
    configurationAvailable: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeviceDto
     */
    healthInfoUrl?: string | null;
}


