// tslint:disable
/**
 * Bordex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
    /**
     * 
     * @type {boolean}
     * @memberof OrderDto
     */
    completed: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    deliveryDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    deviceHostname: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    deviceSite: string;
    /**
     * 
     * @type {number}
     * @memberof OrderDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    shipDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    shipTrackingUrl?: string | null;
    /**
     * One of the following: Ordered, Planned, Shipped, Delivered, Provisioned.
     * @type {string}
     * @memberof OrderDto
     */
    status: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDto
     */
    delivered: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDto
     */
    shipped: boolean;
}


