// tslint:disable
/**
 * Bordex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SiteDto
 */
export interface SiteDto {
    /**
     * 
     * @type {number}
     * @memberof SiteDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SiteDto
     */
    name: string;
}


